import type { Metadata } from "next";
import { Sansation  } from "next/font/google";
import "./globals.css";
import Header from '../components/Header';

const SansationSans = Sansation({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${SansationSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
